[윤현묵] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/24-westagram-backend pull request #40
Opened 2021-08-22 17:16 UTC by fall031-muk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- app생성 시 users가 아닌 hyeonmuk 이름으로 하였는데, 바꿀 수 있나요?? 모든 파일 내의 hyeonmuk를 users로 바꾸고 실행하여 보았는데 오류가 나서 다시 원래대로 수정하였습니다...

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/views.py
> +from hyeonmuk.models import User
import문에도 컨벤션이 있습니다!
파이썬 자체 모듈
Django 모듈
내가 만든 클래스
위와 같은 순서대로 import 하는 객체들을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/urls.py
> +from django.urls.resolvers import URLPattern
사용하지 않는 모듈은 지워주세요.

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/urls.py
> +from hyeonmuk.views import UsersView
현묵님 앱 이름은 보통 기능별로 작성합니다. user에 해당하는 로직을 담당하는 앱은 users로 주로 생성합니다.

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"Duplication_ERROR"}, status=400)
👍  이렇게 작성했을 경우의 이점을 고민하고 블로깅해주세요!

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"Password_Validation_ERROR"}, status=400)
파이썬에서는 `if 조건문` 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  `== False` `== None` `== 0`등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 `not` 을 활용해보세요!

2021-08-23 02:26 UTC, redsaumon commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"NotInput_ERROR"}, status=400)
return message는 다 대문자로 통일해주세요!

2021-08-23 07:29 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/views.py
> +from hyeonmuk.models import User
넵!! 수정했습니다

2021-08-23 07:29 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/urls.py
> +from django.urls.resolvers import URLPattern
네네 지웠습니다~

2021-08-23 07:30 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/urls.py
> +from hyeonmuk.views import UsersView
네네 users로 수정했습니다

2021-08-23 07:30 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"Password_Validation_ERROR"}, status=400)
if not을 활용했습니다~~

2021-08-23 07:30 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"NotInput_ERROR"}, status=400)
대문자로 통일했습니다!!

2021-08-23 08:58 UTC, fall031-muk commented on students/hyeonmuk/hyeonmuk/views.py
> +                return JsonResponse({"message":"Duplication_ERROR"}, status=400)
코드의 내용은 User의 객체에서 email에 해당하는 것만 필터링하여 불러와서 존재하는지 판단하여 존재할 시 중복에러를 발생시키는 작업입니다.
이 방법이 효율적인 이유는 다음과 같습니다.
상위 코드는 DB에 어떤 쿼리도 전달하지 않습니다. DB에 아무런 메시지도 전달하지 않기 때문에 장점으로 볼 수 있습니다. 왜냐하면 DB에 쿼리를 전달하게 되면 웹 애플리케이션을 느려지게 하기 때문입니다. DB의 레코드를 진짜로 가져오기 위해서는 for문으로 쿼리셋을 순회해야하는데 이 경우 DB의 레코드를 실제로 가져오고 장고 모델로 변환되므로 속도적으로 조금 불리할 수 있습니다.

또한 exists()의 경우 쿼리셋 캐시를 만들지 않으면서 레코드가 존재하는지 검사합니다.
(쿼리셋에 if문으로 존재여부를 판단하게 되면(True/False) if문 때문에 쿼리셋이 '평가'되고 이에 따라 쿼리셋 캐시에도 전체 레코드가 저장되어 비효율적입니다.)
따라서 DB에서 가져온 레코드가 하나도 없다면 트래픽과 메모리를 절약할 수 있습니다.
(레코드의 데이터가 커질수록 데이터를 한번에 가져오는 것이 매우 비효율적입니다)

2021-08-23 09:19 UTC, S2-J1NG requested changes

2021-08-23 09:19 UTC, S2-J1NG commented on students/hyeonmuk/users/views.py
> +                return JsonResponse({"message":"KEY_ERROR"}, status=400)
이메일와 비밀번호 정규표현식 작성 하셨는데 이 로직을 사용한 이유가 있을까요?!

2021-08-23 09:42 UTC, fall031-muk commented
![westagram_users](https://user-images.githubusercontent.com/80630313/130426260-69faa69b-d6cb-4f22-a5d2-c3ddcb8b75b1.png)

2021-08-23 10:38 UTC, fall031-muk commented on students/hyeonmuk/users/views.py
> +                return JsonResponse({"message":"KEY_ERROR"}, status=400)
- 이메일이나 패스워드가 전달되지 않을 경우, **`{"message": "KEY_ERROR"}, status code 400` 을 반환합니다.**
에 해당하는 로직을 작성한 것인데, 살펴보니 전체적으로 try, except로 key에러를 잡아줘서 중복된 표현인 것 같습니다.

2021-08-24 02:01 UTC, redsaumon commented
수고하셨습니다 현묵님!

2021-08-24 02:01 UTC, merged

2021-08-24 02:20 UTC, fall031-muk commented
감사합니다~~~