[손명희] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/24-westagram-backend pull request #46
Opened 2021-08-23 05:56 UTC by melody-story

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-23 07:28 UTC, redsaumon reviewed
import문도 컨벤션이 있습니다! 수정해주세요~ 

- 파이썬 자체 모듈
- Django 모듈
- 내가 만든 클래스
위와 같은 순서대로 import 하는 객체들을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

2021-08-23 07:28 UTC, redsaumon commented on students/myeonghee/users/views.py
> +                return JsonResponse({"MESSAGE" : "KEY_ERROR"}, status=400)
try, except문으로 key error를 잡아주셨기 때문에 불필요한 로직입니다.

2021-08-23 07:28 UTC, redsaumon commented on students/myeonghee/users/views.py
> +            else:
else문이 없어도 상위 로직을 타지 않는다면 자연스럽게 실행됩니다. 아래 else문도 지워주세요.

2021-08-23 07:28 UTC, redsaumon commented on students/myeonghee/users/views.py
> +                    return JsonResponse({"MESSAGE" : "비밀번호 형식을 지켜주세요"}, status=404)
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요! 아래 email도 동일합니다.
http 통신은 글로벌하게 사용됩니다. return message도 결국 노출되는 값이기 때문에 규칙성 있게 작성해주세요. 보통 영문 대문자를 사용합니다.

2021-08-23 07:28 UTC, redsaumon commented on students/myeonghee/users/views.py
> +            return JsonResponse({"MESSAGE" : "CREATE"}, status=201)
하나의 PR에는 해당하는 기능의 코드만 올려주세요!

2021-08-23 09:40 UTC, melody-story commented on students/myeonghee/users/views.py
> +            return JsonResponse({"MESSAGE" : "CREATE"}, status=201)
연우님 수정사항 리뷰 부탁드립니다~!!

2021-08-23 09:49 UTC, S2-J1NG requested changes

2021-08-23 09:49 UTC, S2-J1NG commented on students/myeonghee/users/urls.py
import 컨벤션 확인 후 공백 삭제해주세요
위코드 컨벤션은 노션에도 있으니 참고 해주세요!
https://www.notion.so/wecode/wecode-Python-Coding-Convention-0a293f18b2244dfeb1005273d0a9dc75

2021-08-23 09:49 UTC, S2-J1NG commented on students/myeonghee/users/views.py
>  # Create your views here.
불필요한 주석은 삭제해주세요~!

2021-08-23 09:49 UTC, S2-J1NG commented on students/myeonghee/users/urls.py
>  app_name="users"
`app_name` 추가한 이유가 있을까요? 불필요한 내용으로 삭제해주세요!

2021-08-23 09:51 UTC, S2-J1NG commented
`httpie`로 서로 다른 계정 10개 회원가입 해주세요!

2021-08-23 10:07 UTC, melody-story commented
<img width="679" alt="스크린샷 2021-08-23 오후 6 54 50" src="https://user-images.githubusercontent.com/77363145/130429818-c823aa04-67f2-4bbd-8f3f-20f79bdda32f.png">

2021-08-23 10:07 UTC, melody-story commented on students/myeonghee/users/urls.py
>  app_name="users"
수정사항 리뷰 부탁드립니다~!!!

2021-08-24 02:02 UTC, redsaumon commented on students/myeonghee/users/views.py
> +from django.shortcuts import render
사용하지 않는 모듈은 지워주세요!

2021-08-24 02:02 UTC, redsaumon commented on students/myeonghee/users/views.py
> +            password_validator = check_password.match(data['password'])
제일 긴 변수명 기준으로 = 정렬해주세요!

2021-08-24 02:02 UTC, redsaumon commented on students/myeonghee/users/views.py
> +            email_validator = check_email.match(data["email"])
제일 긴 변수명 기준으로 = 정렬해주세요!

2021-08-24 02:02 UTC, redsaumon commented on students/myeonghee/users/views.py
> +            else :
else문 없이도 동작하는 코드입니다 지워주세요!

2021-08-24 04:09 UTC, melody-story commented on students/myeonghee/users/views.py
> +            else :
연우님 수정사항 확인 부탁드립니다!

2021-08-24 05:08 UTC, S2-J1NG approved these changes

2021-08-24 05:24 UTC, merged