[신우주] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/24-westagram-backend pull request #47
Opened 2021-08-23 06:00 UTC by shinwooju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-23 07:56 UTC, S2-J1NG commented on students/wooju/users/views.py
> +                return JsonResponse({'MESSAGE':'EMPTY_ERROR'}, status=400)
아래 정규 표현식으로 처리한 로직과 이 부분이 어떻게 다른가요?

2021-08-23 07:56 UTC, S2-J1NG commented on students/wooju/users/views.py
> +                return JsonResponse({'MESSAGE':'DUPLICATE_EMAIL'}, status=400)
`ALREADY EXISTED EMAIL` 같은 메세지가 더 적절해 보입니다.

2021-08-23 07:56 UTC, S2-J1NG commented on students/wooju/users/views.py
> +                password      = data['password'],
세션 때 배운 bcrypt 적용해서 암호화 적용해주세요!

2021-08-23 08:05 UTC, S2-J1NG commented on students/wooju/westagram/urls.py
> +    path('users', include('users.urls')),
`/users` 로 작성해야 합니다~

2021-08-23 08:07 UTC, shinwooju commented on students/wooju/users/views.py
> +                return JsonResponse({'MESSAGE':'DUPLICATE_EMAIL'}, status=400)
수정완료했습니다.

2021-08-23 08:07 UTC, shinwooju commented on students/wooju/westagram/urls.py
> +    path('users', include('users.urls')),
수정완료했습니다.

2021-08-23 08:37 UTC, shinwooju commented on students/wooju/users/views.py
> +                return JsonResponse({'MESSAGE':'EMPTY_ERROR'}, status=400)
정규표현식에 공백에 대한 정규표현식값을 지정해주지 않았기 때문에 위의 조건문이 필요하지 않습니다.
이메일과 패스워드에 공백을넣어도 정규표현식 외의 값이기 때문에 각 오류메세지를 출력합니다.

2021-08-23 09:23 UTC, S2-J1NG requested changes

2021-08-23 09:23 UTC, S2-J1NG commented on students/wooju/westagram/urls.py
> +    path('/users', include('users.urls')),
우주님 아까 잘못 안내 드린 부분 삭제해주세요~!

2021-08-23 09:23 UTC, S2-J1NG commented on students/wooju/users/urls.py
> +    path('', UsersView.as_view()),
app의 url에 적절한 이름 붙혀주세요!

2021-08-23 10:44 UTC, shinwooju commented on students/wooju/westagram/urls.py
> +    path('/users', include('users.urls')),
네 삭제했습니다

2021-08-23 10:44 UTC, shinwooju commented on students/wooju/users/urls.py
> +    path('', UsersView.as_view()),
/sign-up 만들어주었습니다.

2021-08-24 02:11 UTC, redsaumon commented on students/wooju/users/views.py
> +            user = User.objects.create(
사용하지 않는 변수는 지워주세요! 이것만 하면 바로 머지입니다~!

2021-08-24 02:19 UTC, shinwooju commented on students/wooju/users/views.py
> +            user = User.objects.create(
수정완료했습니다~! 감사합니다

2021-08-24 02:19 UTC, merged

2021-08-24 02:19 UTC, redsaumon commented
우주님 수고하셨습니다!:+1::+1: